### ISSUE TITLE
Wallet Description

### ISSUE THREAD

**Issue by tcblack** [Gridcoin-Project/website#1]
In the question "What is the wallet" the partial answer given is "The Gridcoin wallet works a lot like the wallet you use on a daily basis. Its function is to store your Gridcoin, as well as allowing you to receive and send payments."
However, isn't the more technically correct answer "The Gridcoin Wallet works a lot like the wallet you use on a daily basis.  It's function isn't to hold the coins (Those are on the actual Blockchain), it holds the keys that identify those keys as yours."

**Comment by Gridcoin-Project** [comment]
You are correct. I am aiming to hit a happy medium between being 100% technically correct, and allowing a visitor with limited knowledge of crypto to understand what their wallet is. I missed that balance here.

I have updated to:

The Gridcoin wallet works a lot like the wallet you use on a daily basis.  While it does not hold your coins themselves (these are stored on the blockchain), the wallet holds the keys that allow you to access your coins. The wallet also enables you to receive and send payments.
