### ISSUE TITLE
"What is BOINC" possible rephrasing.

### ISSUE THREAD

**Issue by jring-o** [Gridcoin-Project/website#10]
> BOINC is an open-source, distributed compute platform designed to support volunteer computing, and developed by the University of California, Berkeley. It enables researchers to distribute their research workload to huge networks of computers all across the globe, which are provided by volunteers. Gridcoin rewards your volunteer research work done through the BOINC platform.

TO

> BOINC is an open-source, distributed **computing platform developed at the University of California, Berkeley** and designed to support volunteer computing. It enables researchers to distribute their research workload **across a globally distributed network of computers hosted by volunteers.** Gridcoin rewards your volunteer research work done **on** the BOINC platform.

**Comment by Gridcoin-Project** [comment]
I agree a rephrasing is in order. I have adopted your suggestion, with one minor change:

BOINC is an open-source, distributed computing platform developed at the University of California, Berkeley and designed to support volunteer computing. It enables researchers to distribute their research workload across a globally distributed network of computers **owned** by volunteers. Gridcoin rewards your volunteer research work done on the BOINC platform.

I am concerned people may not understand the term 'hosted'.
