### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jimbo-slice** [Gridcoin-Project/website#3]
Get some Gridcoin! section -- "is is" should be "it is"

While **is is** possible to buy GRC with tether currencies on some exchanges, the most common trading pairs are BTC-GRC and ETH-GRC.

Below is a list of the major exchanges which support Gridcoin, together accounting for 99% of all trade volume.

**Comment by Gridcoin-Project** [comment]
You're on fire - thank you! Fixed.
