### ISSUE TITLE
Stock photos and testimonials.

### ISSUE THREAD

**Issue by jring-o** [Gridcoin-Project/website#6]
Do we want to be using stock photos?
Do we want to have testimonials on the site?

I think both of these harm the credibility of the site.  Makes it feel "sketchy" or like a hyped up ICO site.

**Comment by tcblack** [comment]
Testimonials?  I don't believe they hurt the site credibility.  It would be more helpful perhaps if additional testimonials taken from Reddit threads or something like that were used.

But stock photos?  I agree that they are potentially damaging.

**Comment by Gridcoin-Project** [comment]
Fair comments. Some are stock, most are not. If you look at the websites of other cryptos, most of them use stock photos, or photos verify-ably not of the people named.

I would be very open to having more user testimonials, that would be great!

Stock will all be replaced as soon as the people provide me images. The exception is Rob, who I do not think will ever provide a picture as he is actively using a pseudonym.

**Comment by jring-o** [comment]
Put a "Photo Not Available" or a Gridcoin logo for anyone without a photo.

Testimonials are advertising.  What?  We're a company?  Someone help explain how they are not harmful and don't make it look like a scam ICO site = ).

**Comment by jring-o** [comment]
What if we change the word from "mined" to "minted."

Mining is a word with a definition in the industry.  Proof of Research means creating blocks through research.  Mining through PoR means earning Gridcoin when you create blocks through research.  Neither of these are what Gridcoin does.

**Comment by GeeBell** [comment]
I think Rob's picture should be changed. Part of Gridcoin's community allure is the semi-mystery around Mr. Halförd. I saw this being raised on Slack a few days ago and Dutch seemed to agree that creating a blank figure icon would be superior.

**Comment by Gridcoin-Project** [comment]
Stock photos have been modified. I am not removing the testimonials unless there is a very good reason to do so. That being said, I am open to changing them.
