### ISSUE TITLE
Mistaken Terminology - Proof of Research

### ISSUE THREAD

**Issue by jring-o** [Gridcoin-Project/website#7]
>Mined with POR 
>
>Gridcoin is mined by Proof of Research: completing research work for real organisations and universities, which are working to tackle real problems. You have full control what projects you contribute to with your machine.

Gridcoin is not mined with PoR.  It is not really mined at all and does not use any PoR protocol.  Proof of Research implies securing the blockchain with the statistic "Research."  If we implement CBR, we will mine GRC with PoS and we mint GRC through a secondary incentive structure based off of BOINC stats.  For the time being, Gridcoin is not mined.

**Comment by Gridcoin-Project** [comment]
Mining is essentially connected with crypto today, we would go against the whole industry by ditching the phrase. Gridcoin invented the phrase POR, it does not imply anything other than what Gridcoin says it does.

> we will mine GRC with PoS and we mint GRC through a secondary incentive structure based off of BOINC stats

This is how you confuse everyone that looks into GRC, with zero benefit to us.

**Comment by jring-o** [comment]
What if we change the word from "mined" to "minted."

Mining is a word with a definition in the industry. Proof of Research means creating blocks through research. Mining through PoR means earning Gridcoin when you create blocks through research. Neither of these are what Gridcoin does.

Not sure if you get notifications for comments on closed issues, so I'm tagging you = ).  @Gridcoin-Project
